# Generated by Django 4.1.7 on 2023-03-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='телеграм id')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='имя пользователя')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание товара')),
                ('characteristics', models.JSONField(blank=True, null=True, verbose_name='характеристики товара')),
                ('other_description', models.TextField(blank=True, null=True, verbose_name='дополнительные описания 1')),
                ('seo_dict', models.TextField(blank=True, null=True, verbose_name='SEO словарь')),
                ('seo_plus', models.TextField(blank=True, null=True, verbose_name='SEO +')),
                ('important', models.TextField(blank=True, null=True, verbose_name='важное о товаре')),
                ('is_active', models.BooleanField(default=True, verbose_name='открыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot_app.appuser', verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=True, verbose_name='сообщение от пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='текущий')),
                ('text', models.TextField(verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot_app.usersession', verbose_name='сессия')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
