# Generated by Django 4.1.7 on 2023-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='keywords',
        ),
        migrations.AddField(
            model_name='usersession',
            name='seo_user',
            field=models.TextField(blank=True, null=True, verbose_name='пользовательские SEO слова'),
        ),
    ]
