# Generated by Django 4.1.7 on 2023-03-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seowb',
            old_name='frase',
            new_name='phrase',
        ),
    ]
