# Generated by Django 4.1.7 on 2023-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='other_descriptions',
        ),
        migrations.AddField(
            model_name='usersession',
            name='other_descriptions_1',
            field=models.TextField(blank=True, null=True, verbose_name='дополнительные описания 1'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='other_descriptions_2',
            field=models.TextField(blank=True, null=True, verbose_name='дополнительные описания 2'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='other_descriptions_3',
            field=models.TextField(blank=True, null=True, verbose_name='дополнительные описания 3'),
        ),
    ]
