# Generated by Django 4.1.7 on 2023-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoWB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=255, verbose_name='фраза')),
                ('frequency', models.BigIntegerField(verbose_name='частота')),
            ],
        ),
    ]
