# Generated by Django 4.1.7 on 2023-03-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0002_rename_frase_seowb_phrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='seo_phrases',
        ),
    ]
