# Generated by Django 4.1.7 on 2023-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0002_remove_usersession_keywords_usersession_seo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='обновлена'),
        ),
    ]
