# Generated by Django 4.1.7 on 2023-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0002_message_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='телеграм id'),
        ),
    ]
