# Generated by Django 4.1.7 on 2023-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0002_seowb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='style',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='стиль'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='other_description',
            field=models.TextField(blank=True, null=True, verbose_name='дополнительное описание'),
        ),
    ]
