# Generated by Django 4.1.7 on 2023-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0003_remove_usersession_seo_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='seo_phrases',
            field=models.TextField(blank=True, null=True, verbose_name='SEO фразы'),
        ),
    ]
