# Generated by Django 4.1.7 on 2023-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0003_alter_usersession_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='style',
            field=models.CharField(default='regular', max_length=15, verbose_name='стиль'),
        ),
    ]
