# Generated by Django 4.1.7 on 2023-03-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0004_usersession_seo_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='key_words',
            field=models.TextField(blank=True, null=True, verbose_name='SEO фразы'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='minus_words',
            field=models.TextField(blank=True, null=True, verbose_name='SEO фразы'),
        ),
    ]
