# Generated by Django 4.1.7 on 2023-03-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0005_usersession_key_words_usersession_minus_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='seo_phrases',
            new_name='key_phrases',
        ),
    ]
