# Generated by Django 4.1.7 on 2023-03-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0006_rename_seo_phrases_usersession_key_phrases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='key_phrases',
            new_name='seo_phrases',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='key_words',
        ),
    ]
