# Generated by Django 4.1.7 on 2023-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot_app', '0007_rename_key_phrases_usersession_seo_phrases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='SEO фразы'),
        ),
    ]
